### ISSUE TITLE
error building when disconnected

### ISSUE THREAD

**Issue by jpsala** [yyx990803/register-service-worker#15]
Hi, when working disconnected I get this error:
registerServiceWorker Error during service worker registration: TypeError: Failed to register a ServiceWorker: ServiceWorker script evaluation failed
in network I see that https://storage.googleapis.com/workbox-cdn/releases/3.6.3/workbox-sw.js is trying to get downloaded.
Sorry for my english

**Comment by ulivz** [comment]
Try [Using Local Workbox Files Instead of CDN](https://developers.google.com/web/tools/workbox/modules/workbox-cli#copylibraries).

This issue should be closed.
